### ISSUE TITLE
can't start the project

### ISSUE THREAD

**Issue by spartaelcid** [mys/oretro-bot#1]
Hello,

i modify all login/pwd as read in the readme.md.
But when i try to run the HTTP they don't start and give me this error:
$ node www/server.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'E:\Progetti\oretro-bot\www\www\server.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

(i just add the package.json with npm i-g)

**Comment by mys** [comment]
This code is very old. 2 years ago I was using node v4.2.1.
Im not sure if this project is runnable on node 8+/10+ versions.

**Comment by Nitesh639** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
Skaronator, @calipsow, @jthmiranda, @jez87, @krtk6160, @norikt, @impzero, @rodalbert, @izumis007, @hobart2020, @twpryor, @Clark-zhang, @ID-GuUser, @pavaopahljina, @Imanmahmoodi, @Jessie-1, @tsnieman, @confettimoney, @Devilinheaven234, @nrobi144
